import { useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { db } from '../lib/db'
import type { Account, Contact } from '../lib/types'
import { ErrorBox } from './ui'

// AI email pitch for one account. Generated by the `pitch` edge function; editable before sending.
export default function Pitch({ account, contacts }: { account: Account; contacts: Contact[] }) {
  const [subject, setSubject] = useState('')
  const [body, setBody] = useState('')
  const [busy, setBusy] = useState(false)
  const [err, setErr] = useState('')
  const [copied, setCopied] = useState(false)
  const to = contacts.find(c => c.email)?.email ?? ''

  async function generate() {
    setBusy(true); setErr('')
    try {
      const { data, error } = await supabase.functions.invoke<{ subject?: string; body?: string; error?: string }>('pitch', { body: { account_id: account.id } })
      if (error) {
        const ctx = (error as { context?: Response }).context
        const j = ctx ? await ctx.json().catch(() => null) : null
        throw new Error(j?.error || error.message)
      }
      if (data?.error) throw new Error(data.error)
      setSubject(data?.subject ?? ''); setBody(data?.body ?? '')
    } catch (e) { setErr((e as Error).message) } finally { setBusy(false) }
  }

  async function copy() {
    await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`)
    setCopied(true); setTimeout(() => setCopied(false), 2000)
  }

  async function logSent() {
    await db.activities.insert({ account_id: account.id, opportunity_id: null, type: 'email', summary: `Sent pitch: ${subject}` })
    await db.accounts.update(account.id, { last_activity: new Date().toISOString().slice(0, 10), ...(account.status === 'target' ? { status: 'contacted' } : {}) })
  }

  const mailto = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`

  return (
    <section className="mt-6 border-t border-steel-700 pt-4">
      <div className="flex items-center justify-between mb-2">
        <h3 className="font-medium">Email pitch</h3>
        <button type="button" className="btn-ghost" disabled={busy} onClick={generate}>{busy ? 'Writing…' : subject ? '↻ Regenerate' : '✦ Generate pitch'}</button>
      </div>
      {err && <ErrorBox msg={err} />}
      {!subject && !err && <p className="text-sm text-steel-400">Gemini writes a short email: what we sell, why it fits {account.company}, our contact details. Fill <Link to="/settings" className="text-brand">Our company</Link> first so the signature is right.</p>}
      {subject && (
        <div className="space-y-2">
          <input className="input font-medium" value={subject} onChange={e => setSubject(e.target.value)} />
          <textarea className="input text-sm leading-relaxed" rows={12} value={body} onChange={e => setBody(e.target.value)} />
          <div className="flex flex-wrap gap-2 justify-end">
            <button type="button" className="btn-ghost" onClick={copy}>{copied ? 'Copied ✓' : 'Copy'}</button>
            <a className="btn-primary" href={mailto} onClick={logSent}>Open in email app{to ? ` → ${to}` : ''}</a>
          </div>
          {!to && <p className="text-xs text-amber-300">No contact email on this account — add one under Contacts, or paste the text into WhatsApp/LinkedIn.</p>}
        </div>
      )}
    </section>
  )
}
